services:
  db:
    container_name: db
    image: postgres:16.0
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - back-tier
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password
    restart: on-failure
secrets:
  postgres_user:
    file: ./postgres_user.txt
  postgres_password:
    file: ./postgres_password.txt
networks:
  back-tier:
volumes:
  db-data: