package router

import (
    "github.com/gin-gonic/gin"

    "otakuverse-api/pkg/openapi"
    "otakuverse-api/src/utils"
)

const baseURL = "/api/v1"


func (h *OpenAPIHandlers) GetCredentialsConnect(c *gin.Context) {
    // non implemented func
    if c == nil {
        return
    }
    return
}

func (h *OpenAPIHandlers) PostCredentialsUser(c *gin.Context) {
    // non implemented func
    if c == nil {
        return
    }
    return
}

func (h *OpenAPIHandlers) DeleteCredentialsUser(c *gin.Context) {
    // non implemented func
    if c == nil {
        return
    }
    return
}

func (h *OpenAPIHandlers) PatchCredentialsUser(c *gin.Context) {
    // non implemented func
    if c == nil {
        return
    }
    return
}

func (h *OpenAPIHandlers) GetUserWorks(c *gin.Context, username string) {
    // non implemented func
    if c == nil {
        return
    }
    return
}

func (h *OpenAPIHandlers) DeleteUserWork(c *gin.Context, username string, bookID int) {
    // non implemented func
    if c == nil {
        return
    }
    return
}

func (h *OpenAPIHandlers) PatchUserWork(c *gin.Context, username string, bookID int) {
    // non implemented func
    if c == nil {
        return
    }
    return
}

func (h *OpenAPIHandlers) GetWorks(c *gin.Context, username string) {
    // non implemented func
    if c == nil {
        return
    }
    return
}

func (h *OpenAPIHandlers) DeleteWork(c *gin.Context, id int) {
    // non implemented func
    if c == nil {
        return
    }
    return
}

func (h *OpenAPIHandlers) PostWork(c *gin.Context) {
    // non implemented func
    if c == nil {
        return
    }
    return
}

func (h *OpenAPIHandlers) GetAuthors(c *gin.Context) {
    // non implemented func
    if c == nil {
        return
    }
    return
}

func (h *OpenAPIHandlers) PostAuthor(c *gin.Context) {
    // non implemented func
    if c == nil {
        return
    }
    return
}

func (h *OpenAPIHandlers) DeleteAuthor(c *gin.Context) {
    // non implemented func
    if c == nil {
        return
    }
    return
}

// OpenAPIHandlers Implementaion of the autogenerated ServerInterface
type OpenAPIHandlers struct {
}

// SetupRouter configures Gin Router for API
func SetupRouter() *gin.Engine {
    if utils.GetConfig().Env == "PROD" {
        gin.SetMode(gin.ReleaseMode)
    }
    router := gin.New()
    router.Use(gin.Recovery())

    if err := router.SetTrustedProxies(utils.GetConfig().GinTrustedProxies); err != nil {
        panic(err)
    }
    ginOptions := openapi.GinServerOptions{
        BaseURL: baseURL,
    }
    openAPIHandler := &OpenAPIHandlers{}
    openapi.RegisterHandlersWithOptions(router, openAPIHandler, ginOptions)
    return router
}
